[project]
name = "abc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alex", email = "mail@mail.ru" }
]
requires-python = ">=3.8"
dependencies = [
    "matplotlib>=3.7.5",
    "numpy>=1.24.4",
    "pandas>=2.0.3",
]

[project.scripts]
abc = "abc:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
